version: '2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    restart: always
    environment:
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es01:/usr/share/elasticsearch/data
      - ./config/es01/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./logs/es01:/usr/share/elasticsearch/logs
      - ./plugins/elasticsearch-analysis-ik-7.8.0:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-7.8.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es02
    restart: always
    environment:
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es02:/usr/share/elasticsearch/data
      - ./config/es02/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./logs/es02:/usr/share/elasticsearch/logs
      - ./plugins/elasticsearch-analysis-ik-7.8.0:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-7.8.0
    depends_on:
      - es01
    networks:
      - esnet
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es03
    restart: always
    environment:
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es03:/usr/share/elasticsearch/data
      - ./config/es03/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./logs/es03:/usr/share/elasticsearch/logs
      - ./plugins/elasticsearch-analysis-ik-7.8.0:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-7.8.0
    depends_on:
      - es01
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - SERVER_NAME=kibana
      - SERVER_HOST="0"
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - elasticsearch_ssl_verificationMode=none
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - esnet
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      #- ./nginx/conf.d:/etc/nginx/conf.d 
      #- ./nginx/log:/var/log/nginx
      #- ./nginx/wwwroot:/usr/share/nginx/wwwroot
      - ./nginx/templates:/etc/nginx/templates
    environment:
      #- NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - 8080:80
    networks:
      - esnet
networks:
  esnet: